In [12]:
import tensorflow as tf
data1 = tf.constant([[6,6]])
data2 = tf.constant([[2],
                     [2]])
data3 = tf.constant([[3,3]])
data4 = tf.constant([[1,2],
                    [3,4],
                    [5,6]])
print(data4.shape)#显示维度
matMul = tf.matmul(data1,data2)
matMul2 = tf.multiply(data1,data2)#不符合矩阵乘法，普通乘法
matAdd = tf.add(data1,data3)
with tf.Session() as sess:
    print(sess.run(data4))#打印整体
    
    print(sess.run(data4[0]))#打印某一行
    print(sess.run(data4[:,0]))#打印某一列
    print(sess.run(data4[0,0]))
    print(sess.run(matMul))
    print(sess.run(matMul2))
    print(sess.run(matAdd))
    print(sess.run([matMul,matAdd]))#一次打印多个内容

(3, 2)
[[1 2]
 [3 4]
 [5 6]]
[1 2]
[1 3 5]
1
[[24]]
[[12 12]
 [12 12]]
[[9 9]]
[array([[24]]), array([[9, 9]])]
