In [23]:
import numpy as np
data1 = np.array([1,2,3,4,5])
print(data1)
data2 = np.array([[1,2],
                  [3,4]])
print(data2)
print(data1.shape)
print(data2.shape)
print(np.zeros([2,3]),np.ones([2,2]))
data2[1,0] = 5
print(data2)
print(data2[1,1])
data3 = np.ones([3,2])
print(data3*2)
print(data3/3)
print(data3+2)
data4 = np.array([[1,2,3],
                [4,5,6]])



[1 2 3 4 5]
[[1 2]
 [3 4]]
(5,)
(2, 2)
[[0. 0. 0.]
 [0. 0. 0.]] [[1. 1.]
 [1. 1.]]
[[1 2]
 [5 4]]
4
[[2. 2.]
 [2. 2.]
 [2. 2.]]
[[0.33333333 0.33333333]
 [0.33333333 0.33333333]
 [0.33333333 0.33333333]]
[[3. 3.]
 [3. 3.]
 [3. 3.]]


AttributeError: module 'numpy' has no attribute 'fill'